### ISSUE TITLE
Getting Babel error while adding this library

### ISSUE THREAD

**Issue by getreup** [BBB/react-native-card.io#11]
I'm not sure what is up, but I cannot require card.io.  Can you make any sense out of this error?

TransformError: /Users/kelseyregan/BitBucket/React-Native-Core/Project/node_modules/react-native-card.io/lib/index.js: [BABEL] /Users/kelseyregan/BitBucket/React-Native-Core/Project/node_modules/react-native-card.io/lib/index.js: Unknown option: /Users/kelseyregan/BitBucket/React-Native-Core/Project/node_modules/react-native-card.io/.babelrc.stage

**Comment by BBB** [comment]
@KelseyRegan I'd guess this is an issue with the version of babel tied to the react-native you're using. What version of react-native is it?

**Comment by KimberleyCook** [comment]
@KelseyRegan I had to exclude node_modules when loading in babel in my webpack.config file and delete the .babelrc file from the react-native-card.io folder in node_modules, to get it working

**Comment by getreup** [comment]
Thanks, I'll try this out today and report back.

**Comment by getreup** [comment]
No such luck so far.

@BBB Hey Olie, my react-native version is 18-rc

@KimberleyCook Hey Kim, I deleted the .babelrc, but I'm not sure how to go about the first thing you mentioned.  Could you expand on that?

**Comment by davidgruebl** [comment]
@KelseyRegan could be sth. like the snippet below in the loaders section of your webpack config

``` js
{
  test: /\.(js|jsx|es6)$/,
  exclude: /node_modules/,
  loader: 'babel',
  query: {
    cacheDirectory: true,
    presets: ['es2015', 'stage-1', 'react']
  }
}
```

**Comment by lewisbarber** [comment]
Deleting .babelrc worked for me. I didn't need to make the webpack changes
