### ISSUE TITLE
What is the process for cancelling a scan?

### ISSUE THREAD

**Issue by christurnertv** [BBB/react-native-card.io#3]
Thanks for providing this great library. Is there a way to cancel the scan? I didn't see that `cancelScanCard` was exposed. I'm sure I could use a state variable to enable or disable the view but I want to make sure that the used resources are properly freed. Any advice would be greatly appreciated.

**Comment by christurnertv** [comment]
I did some experimentation and this is what I found... I added the CardIO component in a new view that gets pushed onto the navigation stack. I added a button to the component that would pop it off the navigation stack. I monitored the memory usage after doing opening and closing the CardIO view many times. Memory usage would climb slowly, and then come back down a bit. It was like 3 steps forward, 2 steps back.

My app will be running over long periods and the CardIO view will get opened and closed many times. Please advise if you think there are other things that should be done to keep memory usage in check. Thanks in advance!

**Comment by BBB** [comment]
@cturner80 Apologies for the slow response; I've been on holiday.

Popping the view off the nav stack is currently the best way to cancel the card view; or at least the best way I've found.

Hopefully I'll get a chance to look at the memory usage today. I've been focussing on the Android build, so performance optimisation hasn't really been a priority.

**Comment by BBB** [comment]
@cturner80 I've noticed a `preload` method on the card.io interface. https://github.com/card-io/card.io-iOS-SDK/blob/master/CardIO/CardIOUtilities.h#L31

I'm going to add this to the package. Hopefully this might help with the memory issues.

**Comment by BBB** [comment]
I've release `v1.2.0` with the preload method. Let me know how you get on.

**Comment by christurnertv** [comment]
@BBB Excellent, thanks so much! I'll give it a try this week and let you know how it goes.
