### ISSUE TITLE
Error on iOS 7.1.2, System not found (ECMAScript 6)

### ISSUE THREAD

**Issue by xcarpentier** [BBB/react-native-card.io#4]
Error on iOS 7.1.2, System not found (ECMAScript 6).

In file lib/constants.js.

**Comment by BBB** [comment]
This seems like a very strange error. Can you give me more details? Perhaps some code to reproduce the issue.

**Comment by xcarpentier** [comment]
Yes it's strange, but the "Symbol" implementation is not present in the iOS 7.1.2 JavaScript implementation.

![screen shot 2015-11-27 at 13 18 49](https://cloud.githubusercontent.com/assets/923036/11441176/aebdb4e0-9509-11e5-87f1-ee7569ed977c.png)

**Comment by BBB** [comment]
@xcarpentier I've updated the code so that babel won't try to use `Symbol`. Please try using `v1.2.0` instead.

**Comment by xcarpentier** [comment]
Thanks a lot ! 
:+1:
